#' @title Example workflow for RedoxRRI
#'
#' @name redoxrri_example
#'
#' @description
#' Demonstrates a complete RedoxRRI workflow using a synthetic
#' plant-soil-microbiome time-series dataset generated by
#' [simulate_redox_holobiont()].
#'
#' @details
#' This example shows how to:
#'
#' \itemize{
#'   \item Simulate a spatio-temporal holobiont redox dataset.
#'   \item Compute sample-level Redox Resilience Index scores.
#'   \item Inspect compositional Physio-Soil-Micro RRI allocation.
#'   \item Quantify perturbation-recovery metrics.
#'   \item Generate ternary and recovery-metric visualizations.
#' }
#'
#' The simulated dataset contains plant physiological variables, rhizosphere
#' oxygen-flux proxies, soil redox chemistry, hydrological variables,
#' dissolved organic carbon, microbial abundance features, microbial redox
#' trait proxies, and optional functional gene abundance or MetaT-style
#' expression features.
#'
#' The generated data are fully synthetic and are provided for examples,
#' testing, benchmarking, teaching, and method development. They are not
#' calibrated to any specific ecosystem. Users may replace these simulated
#' inputs with their own external datasets, provided that rows are aligned
#' across `id`, `ROS_flux`, `Eh_stability`, and `micro_data`.
#'
#' @examples
#' # Simulate a compact synthetic holobiont redox time series
#' sim <- simulate_redox_holobiont(
#'   n_plot = 2,
#'   n_depth = 1,
#'   n_plant = 2,
#'   n_time = 12,
#'   p_micro = 20,
#'   seed = 1
#' )
#'
#' # Inspect the returned data layers
#' names(sim)
#' head(sim$id)
#' head(sim$ROS_flux)
#' head(sim$Eh_stability)
#' head(sim$micro_data)
#' head(sim$micro_traits)
#'
#' # Combine microbial abundance, trait, and gene-level features
#' micro_features <- cbind(
#'   sim$micro_data,
#'   sim$micro_traits,
#'   log1p(sim$micro_gene_abundance)
#' )
#'
#' # Compute RedoxRRI scores
#' res <- suppressWarnings(rri_pipeline_st(
#'   ROS_flux = sim$ROS_flux,
#'   Eh_stability = sim$Eh_stability,
#'   micro_data = micro_features,
#'   id = sim$id,
#'   reducer = "per_domain",
#'   scaling = "pnorm"
#' ))
#'
#' # Sample-level RRI scores
#' head(res$row_scores)
#'
#' # Compositional Physio-Soil-Micro allocation used for ternary plots
#' head(res$row_scores_comp)
#'
#' # Ternary visualization requires res$row_scores_comp, not recovery metrics
#' # ggtern is not compatible with every ggplot2 release, so attempt the
#' # ternary plot defensively rather than letting it abort the example.
#' if (requireNamespace("ggtern", quietly = TRUE) &&
#'     requireNamespace("ggplot2", quietly = TRUE) &&
#'     requireNamespace("viridis", quietly = TRUE)) {
#'   try(
#'     print(plot_RRI_ternary(
#'       res$row_scores_comp,
#'       point_size = 3,
#'       show_centroid = TRUE
#'     )),
#'     silent = TRUE
#'   )
#' }
#'
#' # Quantify perturbation-recovery metrics from the RRI trajectory
#' rec <- rri_recovery_metrics(
#'   res = res,
#'   id = sim$id,
#'   time_col = "time",
#'   group_cols = c("plot", "depth", "plant_id"),
#'   perturb_start = 5,
#'   perturb_end = 7
#' )
#'
#' head(rec)
#'
#' # Recovery visualizations.
#' # plot_rri_recovery_map() takes the scored pipeline output plus identifiers;
#' # plot_rri_recovery_landscape() takes the metrics table.
#' if (requireNamespace("ggplot2", quietly = TRUE)) {
#'   plot_rri_recovery_map(
#'     res = res,
#'     id = sim$id,
#'     rec = rec,
#'     time_col = "time",
#'     group_cols = c("plot", "depth", "plant_id"),
#'     perturb_start = 5,
#'     perturb_end = 7
#'   )
#' }
#'
#' if (requireNamespace("ggplot2", quietly = TRUE) &&
#'     requireNamespace("tidyr", quietly = TRUE) &&
#'     requireNamespace("tidyselect", quietly = TRUE)) {
#'   plot_rri_recovery_landscape(
#'     rec,
#'     metrics = c("depth_min_frac", "overshoot_frac", "I_norm",
#'                 "k", "tau_lag", "t_half")
#'   )
#' }
#'
#' @seealso
#' [simulate_redox_holobiont()],
#' [rri_pipeline_st()],
#' [rri_recovery_metrics()],
#' [plot_RRI_ternary()],
#' [plot_rri_recovery_landscape()]
NULL
